In [2]:
import numpy as np

In [45]:
B_new = np.matrix(np.zeros([3, 1]))

In [5]:
def class_gen(samples=100):
    mu_1 = np.array([4, 4])
    mu_2 = np.array([-4, -4])
    sigma = np.eye(2, 2)
    class1 = np.random.multivariate_normal(mu_1, sigma, samples)
    class2 = np.random.multivariate_normal(mu_2, sigma, samples)
    return class1, class2

In [6]:
class1, class2 = class_gen()

In [8]:
X = np.vstack([class1, class2])

In [9]:
X.shape

(200, 2)

In [11]:
X = np.hstack([X, np.ones((200, 1))])

In [13]:
X.shape

(200, 3)

In [48]:
p_x_B = np.multiply(np.exp(X*B_new), 1.0/(1.0+np.exp(X*B_new)))

In [49]:
p_1_x_B = 1.0 - p_x_B

In [50]:
MainDiag = np.array(np.multiply(p_x_B, p_1_x_B))

In [51]:
MainDiag = [i[0] for i in MainDiag]

In [52]:
W = np.diag(MainDiag)

In [53]:
W

array([[0.25, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.25]])

In [54]:
def Gradient_Logistic_Regression(X, Y, p_x_B):
    """
    The Logistic Regression Gradient of the likelihhod sum(log p_i). 
    """
    return X.T@(Y-p_x_B)


def Hessian_Inverse_Losgistic(X, Y, W):
    """
    The invers of the Logistic Regression Gradient of the likelihhod 
    sum(log p_i).
    """
    return np.linalg.inv(-X.T@W@X)

In [55]:
Y = np.vstack([np.ones((100, 1)), np.zeros((100, 1))])

In [56]:
Gradient_B = Gradient_Logistic_Regression(X, Y, p_x_B)

In [57]:
Gradient_B

matrix([[400.16820313],
        [394.30977363],
        [  0.        ]])

In [58]:
Gradient_B

matrix([[400.16820313],
        [394.30977363],
        [  0.        ]])

In [59]:
Hessian_B_inv = Hessian_Inverse_Losgistic(X, Y, W)

In [60]:
Hessian_B_inv

array([[-0.00929428,  0.00877213, -0.00036734],
       [ 0.00877213, -0.00947139,  0.00037955],
       [-0.00036734,  0.00037955, -0.02001542]])

In [61]:
B_old = np.copy(B_new)
alpha = 1
B_new = B_old + alpha*Hessian_B_inv*Gradient_B
alpha /=2

In [62]:
B_old

array([[0.],
       [0.],
       [0.]])

In [63]:
B_new

matrix([[-0.26034131],
        [-0.22433362],
        [ 0.00265981]])